package com.amazonaws.xray.plugins;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.HashMap;
import java.util.Map;

import com.amazonaws.xray.utils.DockerUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * A plugin, for use with the {@code AWSXRayRecorderBuilder} class, which will add ECS container information to segments generated by the built {@code AWSXRayRecorder} instance.
 * 
 * @see com.amazonaws.xray.AWSXRayRecorderBuilder#withPlugin(Plugin)
 *
 */
public class ECSPlugin implements Plugin {
    private static final Log logger = LogFactory.getLog(ECSPlugin.class);

    private static final String SERVICE_NAME = "ecs";
    private static final String ECS_METADATA_KEY = "ECS_CONTAINER_METADATA_URI";
    private static final String HTTP_PREFIX = "http://";
    public static final String ORIGIN = "AWS::ECS::Container";
    private static final String CONTAINER_ID_KEY = "containerId";

    private HashMap<String, Object> runtimeContext;
    private DockerUtils dockerUtils;

    public ECSPlugin() {
        runtimeContext = new HashMap<>();
        dockerUtils = new DockerUtils();
    }

    @Override
    /**
     * Returns true if the environment variable added by ECS is present and contains a valid URI
     */
    public boolean isEnabled() {
        String ecsMetadataURI = System.getenv(ECS_METADATA_KEY);
        if (ecsMetadataURI == null) {
            return false;
        }

        return ecsMetadataURI.startsWith(HTTP_PREFIX);
    }

    @Override
    public String getServiceName() {
        return SERVICE_NAME;
    }

    public void populateRuntimeContext() {
        try {
            runtimeContext.put("container", InetAddress.getLocalHost().getHostName());
        } catch (UnknownHostException uhe) {
            logger.error("Could not get docker container ID from hostname.", uhe);
        }

        try {
            runtimeContext.put(CONTAINER_ID_KEY, dockerUtils.getContainerId());
        } catch (IOException e) {
            logger.error("Failed to read full container ID from container instance.", e);
        }
    }

    public Map<String, Object> getRuntimeContext() {
        populateRuntimeContext();
        return runtimeContext;
    }

    @Override
    public String getOrigin() {
        return ORIGIN;
    }

    @Override
    /**
     * Determine equality of plugins using origin to uniquely identify them
     */
    public boolean equals(Object o) {
        if (!(o instanceof Plugin)) { return false; }
        return this.getOrigin().equals(((Plugin) o).getOrigin());
    }

    @Override
    /**
     * Hash plugin object using origin to uniquely identify them
     */
    public int hashCode() {
        return this.getOrigin().hashCode();
    }


}
