on:
  push:
    branches:
      - migrate-sonatype-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle Modules
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build and test
        run: ./gradlew build -Prelease.version=0.0.1-sonatype-test --stacktrace
        env:
          CI: true
      - name: Build and publish to sonatype
        run: ./gradlew final closeAndReleaseSonatypeStagingRepository -Prelease.version=0.0.1-sonatype-test --stacktrace
        env:
          CI: true
          SONATYPE_USERNAME_TEST: ${{ secrets.SONATYPE_USERNAME_TEST }}
          SONATYPE_PASSWORD_TEST: ${{ secrets.SONATYPE_PASSWORD_TEST }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ github.event.inputs.version }}
      #     release_name: Release v${{ github.event.inputs.version }}
      #     draft: true
      #     prerelease: false
